/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package content;

//import static content.Data_pemesanan.tIdPemesanan;
import inc.config;
import java.awt.Dimension;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import static views.login.id;

/**
 *
 * @author LUKAS PUTRA DIANTAMA
 */
public class Data_detail_pemesanan extends javax.swing.JInternalFrame {
    Connection conn = config.Conn();
    Statement st;
    ResultSet rs;
    String idDetail;

   
       private void tampilData(){
       DefaultTableModel model = new DefaultTableModel();
       model.addColumn("No");
       model.addColumn("Detail ID");
       model.addColumn("ID Pemesanan");
       model.addColumn("Nama Obat");
       model.addColumn("Kode Obat");
       model.addColumn("Nama Obat(*)");
       model.addColumn("Satuan");
       model.addColumn("Nama Satuan (*)");
       model.addColumn("Sediaan");
       model.addColumn("Nama Sediaan(*)");
       model.addColumn("Jumlah");
       model.addColumn("Harga pcs");
       model.addColumn("Subtotal");
       bUbah.setEnabled(false);
       bHapus.setEnabled(false);
       String idPemesanan = tidPemesanan2.getText();


       try{
           String sql = "SELECT * FROM sys_pemesanan_detail INNER JOIN sys_pemesanan ON sys_pemesanan_detail.pemesanan_detail_pemesanan_id = sys_pemesanan.pemesanan_id INNER JOIN sys_obat ON sys_obat.obat_id = sys_pemesanan_detail.pemesanan_detail_obat_id INNER JOIN sys_sediaan ON sys_sediaan.sediaan_id = sys_pemesanan_detail.pemesanan_detail_sediaan_id INNER JOIN sys_satuan ON sys_satuan.satuan_id = sys_pemesanan_detail.pemesanan_detail_satuan_id WHERE pemesanan_detail_pemesanan_id = '"+idPemesanan+"'";
           st = conn.createStatement();
           rs = st.executeQuery(sql);
           
           System.out.println(sql);

           int no = 0;
           while(rs.next()){
               no++;
               model.addRow(new Object []{
                   no, rs.getString("pemesanan_detail_id"),rs.getString("pemesanan_detail_pemesanan_id"),rs.getString("obat_name"),rs.getString("pemesanan_detail_obat_barcode"),rs.getString("pemesanan_detail_obat_name"),rs.getString("satuan_name"),rs.getString("pemesanan_detail_satuan_name"),rs.getString("sediaan_name"),rs.getString("pemesanan_detail_sediaan_name"),rs.getString("pemesanan_detail_quantity"),rs.getString("pemesanan_detail_price"),rs.getString("pemesanan_detail_subtotal"),
               });
           }
           tData.setModel(model);
       }catch(Exception e){
           System.out.println(e.getMessage());
       }
    }
    int idKaryawan,idSales,idObat,idSatuan,idSediaan,idPabrik;
    /**
     * Creates new form Data_detail_pemesanan
     */
    public Data_detail_pemesanan() {
        initComponents();
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tData = new javax.swing.JTable()
        {
            public boolean isCellEditable(int rowIndex, int colIndex)
            {
                return false;
            }
        };
        tIdDetail = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tidPemesanan2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        tCari = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        bTambah = new javax.swing.JButton();
        bUbah = new javax.swing.JButton();
        bHapus = new javax.swing.JButton();

        setClosable(true);
        setMaximizable(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 153, 0));

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Detail Pemesanan");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(73, Short.MAX_VALUE))
        );

        tData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NO", "Detail ID", "Nama Obat", "Kode Obat", "Nama Obat", "Satuan", "Nama Satuan", "Sediaan", "Nama Sediaan", "Pabrik", "Jumalh Beli", "Harga pcs", "Subtotal"
            }
        ));
        tData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tDataMouseClicked(evt);
            }
        });
        tData.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tDataKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(tData);

        tIdDetail.setEditable(false);

        jLabel2.setText("ID Pemesanan");

        tidPemesanan2.setEditable(false);

        jLabel3.setText("ID Detail");

        jButton1.setText("Batal");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        tCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tCariKeyPressed(evt);
            }
        });

        jLabel4.setText("Pencarian");

        bTambah.setText("Tambah");
        bTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bTambahActionPerformed(evt);
            }
        });

        bUbah.setText("Ubah");
        bUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bUbahActionPerformed(evt);
            }
        });

        bHapus.setText("Hapus");
        bHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bHapusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bTambah)
                        .addGap(18, 18, 18)
                        .addComponent(bUbah)
                        .addGap(18, 18, 18)
                        .addComponent(bHapus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tCari, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 837, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tidPemesanan2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tIdDetail, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bTambah)
                    .addComponent(jLabel4)
                    .addComponent(tCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(bUbah)
                    .addComponent(bHapus))
                .addGap(19, 19, 19)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tIdDetail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(tidPemesanan2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        tampilData();
       try{
          //tampilData();
          String sql = "SELECT * FROM sys_obat";
          conn = config.Conn();
          st = conn.createStatement();
          rs = st.executeQuery(sql);
          
           while(rs.next()){
              // cObat.addItem(rs.getString("obat_name"));
           }
      }catch(Exception e){
          System.out.println(e.getMessage());
      }  
      //////////////////////////////////////////////
       try{
          String sql = "SELECT * FROM sys_satuan";
          conn = config.Conn();
          st = conn.createStatement();
          rs = st.executeQuery(sql);
          
           while(rs.next()){
               //cSatuan.addItem(rs.getString("satuan_name"));
           }
      }catch(Exception e){
          System.out.println(e.getMessage());
      }
       
          try{
          //tampilData();
          String sql = "SELECT * FROM sys_sediaan";
          conn = config.Conn();
          st = conn.createStatement();
          rs = st.executeQuery(sql);
          
           while(rs.next()){
               //cSediaan.addItem(rs.getString("sediaan_name"));
           }
      }catch(Exception e){
          System.out.println(e.getMessage());
      }  
      //////////////////////////////////////////////
       try{
          String sql = "SELECT * FROM sys_pabrik";
          conn = config.Conn();
          st = conn.createStatement();
          rs = st.executeQuery(sql);
          
           while(rs.next()){
              // cPabrik.addItem(rs.getString("pabrik_name"));
           }
      }catch(Exception e){
          System.out.println(e.getMessage());
      } 
    }//GEN-LAST:event_formInternalFrameOpened

    private void bTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bTambahActionPerformed
       idDetail = tidPemesanan2.getText();
       //System.out.println(idDetail);
       xTambah_pemesanan_detail xtambah_pemesanan_detail = new xTambah_pemesanan_detail();
       xTambah_pemesanan_detail.tIdPemesananSebelumnya.setText(this.idDetail);
       this.getParent().add(xtambah_pemesanan_detail);
         
       Dimension parentSize = this.getParent().getSize();
       Dimension childSize = xtambah_pemesanan_detail.getSize();
        
       xtambah_pemesanan_detail.setLocation((parentSize.width - childSize.width)/2, (parentSize.height-childSize.height)/2);
       xtambah_pemesanan_detail.setVisible(true);
    }//GEN-LAST:event_bTambahActionPerformed

    private void tDataKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tDataKeyPressed
       
        
    }//GEN-LAST:event_tDataKeyPressed

    private void tDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tDataMouseClicked
        int baris = tData.getSelectedRow();
        //
        tIdDetail.setText(tData.getModel().getValueAt(baris, 1).toString());
        //
       
        bUbah.setEnabled(true);
        bHapus.setEnabled(true);
    }//GEN-LAST:event_tDataMouseClicked

    private void bHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bHapusActionPerformed
          if(JOptionPane.showConfirmDialog(null, "Anda Yakin Menghapus Data Ini?","Menghapus Data",JOptionPane.YES_NO_OPTION)== JOptionPane.YES_OPTION){
                try{
                    String sql = "DELETE FROM sys_pemesanan_detail WHERE pemesanan_detail_id = '"+tIdDetail.getText()+"'";
                    st = conn.createStatement();
                    st.executeUpdate(sql);
                    JOptionPane.showMessageDialog(null,"Data Berhasil Dihapus!");
                    tampilData();

                 }catch(Exception e){
                     System.out.println(e.getMessage());
                 }
        }
    }//GEN-LAST:event_bHapusActionPerformed

    private void tCariKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tCariKeyPressed
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("No");
        model.addColumn("Detail ID");
        model.addColumn("Pemesanan ID");
        model.addColumn("Nama Obat");
        model.addColumn("Kode Obat");
        model.addColumn("Nama Obat (*)");
        model.addColumn("Satuan");
        model.addColumn("Nama Satuan(*)");
        model.addColumn("Sediaan");
        model.addColumn("Nama Sediaan(*)");
        model.addColumn("Jumlah");
        model.addColumn("Harga Pcs");
        model.addColumn("Subtotal");
      
        try{
            String sql = "SELECT * FROM sys_pemesanan_detail "
                    + "INNER JOIN sys_satuan ON sys_satuan.satuan_id = sys_pemesanan_detail.pemesanan_detail_satuan_id "
                    + "INNER JOIN sys_sediaan ON sys_sediaan.sediaan_id = sys_pemesanan_detail.pemesanan_detail_sediaan_id "
                    + "WHERE pemesanan_detail_obat_barcode LIKE '%"+tCari.getText()+"%' OR pemesanan_detail_obat_name LIKE '"+tCari.getText()+"'";
            
            st = conn.createStatement();
            rs = st.executeQuery(sql);
            
            int no = 0;
            while(rs.next()){
                no++;
                model.addRow(new Object []{
                    no,rs.getString("pemesanan_detail_id"), rs.getString("pemesanan_detail_pemesanan_id"),rs.getString("pemesanan_detail_obat_id"),rs.getString("pemesanan_detail_obat_barcode"),rs.getString("pemesanan_detail_obat_name"),rs.getString("satuan_name"),rs.getString("pemesanan_detail_satuan_name"),rs.getString("sediaan_name"),rs.getString("pemesanan_detail_sediaan_name"),rs.getString("pemesanan_detail_pabrik_id"),rs.getString("pemesanan_detail_quantity"),rs.getString("pemesanan_detail_price"),rs.getString("pemesanan_detail_subtotal"),
                });
            }
            tData.setModel(model);
        }catch(Exception e){
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_tCariKeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        clearTextCari();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void bUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bUbahActionPerformed
       //idDetail = tidPemesanan2.getText();
       
       //xTambah_pemesanan_detail xtambah_pemesanan_detail = new xTambah_pemesanan_detail();
       //xTambah_pemesanan_detail.tIdPemesananSebelumnya.setText(this.idDetail);
       //this.getParent().add(xtambah_pemesanan_detail);
         
       //Dimension parentSize = this.getParent().getSize();
       //Dimension childSize = xtambah_pemesanan_detail.getSize();
        
       //xtambah_pemesanan_detail.setLocation((parentSize.width - childSize.width)/2, (parentSize.height-childSize.height)/2);
       //xtambah_pemesanan_detail.setVisible(true);
       //idDetail = tidPemesanan2.getText();
       //xEdit_pemesanan xedit_pemesanan = new xEdit_pemesanan();
       //xEdit_pemesanan.tIdPemesananSebelumnya.setText(this.idDetail);
       
       //Dimension parentSize = this.getParent().getSize();
       //Dimension childSize = xedit_pemesanan.getSize();
        
       //xedit_pemesanan.setLocation((parentSize.width - childSize.width)/2, (parentSize.height-childSize.height)/2);
       //xedit_pemesanan.setVisible(true);
       
       
       
    }//GEN-LAST:event_bUbahActionPerformed

    private void clearTextCari(){
        tCari.setText("");
        tampilData();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bHapus;
    private javax.swing.JButton bTambah;
    private javax.swing.JButton bUbah;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField tCari;
    private javax.swing.JTable tData;
    private javax.swing.JTextField tIdDetail;
    public static javax.swing.JTextField tidPemesanan2;
    // End of variables declaration//GEN-END:variables

   

   // public void setidDetail(String idDetail) {
   //     {this.idDetail.getText();}
   // }
    
   // public String getidPemesanan(){
   //     return this.tIdDetail.getText();
   // }
}
