/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package content;

import inc.config;
import java.awt.Dimension;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author LUKAS PUTRA DIANTAMA
 */
public class xTambah_pemesanan2 extends javax.swing.JInternalFrame {

    Connection conn = config.Conn();
    Statement st;
    ResultSet rs;
    int idSales,idKaryawan,tIdPemesanan;
    String idPemesanan,namaSales,hpSales;

    /**
     * Creates new form Tambah_pemesanan2
     */
    public xTambah_pemesanan2() {
        initComponents();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tId = new javax.swing.JTextField();
        tKode = new javax.swing.JTextField();
        cNamaSales = new javax.swing.JComboBox<>();
        cNamaKaryawan = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        tTgl = new com.toedter.calendar.JDateChooser();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setClosable(true);
        setMaximizable(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 153, 0));

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Tambah Pemesanan");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 616, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jLabel2.setText("ID");

        jLabel3.setText("Kode Pemesanan");

        jLabel4.setText("Nama Sales");

        jLabel5.setText("Nama Karyawan");

        tId.setEditable(false);

        cNamaSales.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Nama Sales" }));
        cNamaSales.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                cNamaSalesPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        cNamaKaryawan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Nama Karyawan" }));
        cNamaKaryawan.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                cNamaKaryawanPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        jLabel6.setText("Tanggal Pemesanan");

        jButton1.setText("Batal");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Tambah");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tId)
                    .addComponent(tKode)
                    .addComponent(cNamaSales, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cNamaKaryawan, 0, 160, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(33, 33, 33)
                        .addComponent(tTgl, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(jButton2)
                        .addGap(31, 31, 31)
                        .addComponent(jButton1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(tId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)))
                    .addComponent(tTgl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tKode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cNamaSales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cNamaKaryawan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(0, 18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
          try{
         
          String sql = "SELECT * FROM sys_karyawan";
          conn = config.Conn();
          st = conn.createStatement();
          rs = st.executeQuery(sql);
          
           while(rs.next()){
               cNamaKaryawan.addItem(rs.getString("karyawan_name"));
           }
      }catch(Exception e){
          System.out.println(e.getMessage());
      }  
            try{
          String sql = "SELECT * FROM sys_sales";
          conn = config.Conn();
          st = conn.createStatement();
          rs = st.executeQuery(sql);
          
           while(rs.next()){
              cNamaSales.addItem(rs.getString("sales_name"));
           }
      }catch(Exception e){
          System.out.println(e.getMessage());
      }
    }//GEN-LAST:event_formInternalFrameOpened

    private void cNamaSalesPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cNamaSalesPopupMenuWillBecomeInvisible
         try{
          String sql = "SELECT * FROM sys_sales WHERE sales_name = '"+cNamaSales.getSelectedItem()+"'";
          conn = config.Conn();
          st = conn.createStatement();
          rs = st.executeQuery(sql);
          
          
           if(rs.next()){
               idSales = rs.getInt("sales_id");
           }
      }catch(Exception e){
          System.out.println(e.getMessage());
      } 
    }//GEN-LAST:event_cNamaSalesPopupMenuWillBecomeInvisible

    private void cNamaKaryawanPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cNamaKaryawanPopupMenuWillBecomeInvisible
         try{
          String sql = "SELECT * FROM sys_karyawan WHERE karyawan_name = '"+cNamaKaryawan.getSelectedItem()+"'";
          conn = config.Conn();
          st = conn.createStatement();
          rs = st.executeQuery(sql);
          
          
           if(rs.next()){
               idKaryawan = rs.getInt("karyawan_id");
           }
      }catch(Exception e){
          System.out.println(e.getMessage());
      } 
    }//GEN-LAST:event_cNamaKaryawanPopupMenuWillBecomeInvisible

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String date = sdf.format(tTgl.getDate());
        int  generatedKey = 0; 
         
        String cekKode = tKode.getText().trim().replaceAll("\\s","");
        String cekSales = cNamaSales.getSelectedItem().toString();
        String cekKaryawan = cNamaKaryawan.getSelectedItem().toString();
        String cekTgl = sdf.format(tTgl.getDate());
        Date cekDate;
        cekDate= tTgl.getDate();
        //String cekNamaSales = tNamaSales.getText();
        //String cekHpSales = tHpSales.getText();
        
        if(cekKode.equals("")&&cekSales.equals("Pilih Nama Sales")&&cekKaryawan.equals("Pilih Nama Karyawan")){
          JOptionPane.showMessageDialog(null, "Isi Data Terlebih Dahulu!");
          JOptionPane.showMessageDialog(null, "Data Gagal Ditambahkan!");
        } else if(cekKode.equals("")){
            JOptionPane.showMessageDialog(null, "Kode Pemesanan Tidak Boleh Kosong!");
            JOptionPane.showMessageDialog(null, "Data Gagal Ditambahkan!");
        }else if(cekSales.equals("Pilih Nama Sales")){
            JOptionPane.showMessageDialog(null, "Nama Sales Tidak Boleh Kosong!");
            JOptionPane.showMessageDialog(null, "Data Gagal Ditambahkan!");
        }else if(cekKaryawan.equals("Pilih Nama Karyawan")){
            JOptionPane.showMessageDialog(null, "Nama Karyawan Tidak Boleh Kosong!");
            JOptionPane.showMessageDialog(null, "Data Gagal Ditambahkan!");
        }else{
              if(JOptionPane.showConfirmDialog(null, "Anda Yakin Data Yang Anda Tambahkan Sudah Benar?","Menambahkan Data",JOptionPane.YES_NO_OPTION)== JOptionPane.YES_OPTION){
                  
                //Ambil Nama dan Nomor Telepon SAles
                        try{

                    String sqll ="SELECT * FROM sys_pemesanan INNER JOIN sys_sales ON sys_pemesanan.pemesanan_sales_id = sys_sales.sales_id WHERE pemesanan_id = '"+tIdPemesanan+"' ";
                    //String sqll = "SELECT * FROM sys_pemesanan_detail INNER JOIN sys_pemesanan ON sys_pemesanan.pemesanan_id = sys_pemesanan_detail.pemesanan_detail_pemesanan_id WHERE pemesanan_detail_pemesanan_id = '"+tIdPemesananSebelumnya+"'";
                    conn = config.Conn();
                    st = conn.createStatement();
                    rs = st.executeQuery(sqll);
                    //System.out.println(sqll);


                   if(rs.next()){
                      namaSales = rs.getString("sales_name");
                      hpSales = rs.getString("sales_phone");  
                   }

                }catch(Exception e){
                    System.out.println("Query Error Selctnya Error");
                }
                
                //
                  
                  
                 
                 try{
                    String sql = "INSERT INTO sys_pemesanan VALUES (NULL,'"+cekKode+"', '"+date+"','"+idKaryawan+"', '"+idSales+"', '"+namaSales+"', '"+hpSales+"','pending','0')";
                    PreparedStatement ps = conn.prepareStatement(sql,Statement.RETURN_GENERATED_KEYS);
                    ps.execute();
                    ResultSet rs = ps.getGeneratedKeys();
                    if(rs.next()){
                       generatedKey = rs.getInt(1);
                    }
                    clearText();
                   }catch(Exception e){
                       System.out.println(e.getMessage());
                  }
               }
                JOptionPane.showMessageDialog(null, "Data Berhasil Ditambahkan!");
                //Data_pemesanan main = new Data_pemesanan();    
                //main.setVisible(true);
                this.dispose();
                
        }
        //pindah view ke tambah dtail pemesanan
         //System.out.println(generatedKey);
         ////////String tidPemesanan2 = generatedKey.toString();
         //xTambah_pemesanan_detail xtambah_pemesanan_detail = new xTambah_pemesanan_detail();
         ///////xTambah_pemesanan_detail.tIdPemesananSebelumnya.setText(this.generatedKey);
         //this.getParent().add(xtambah_pemesanan_detail);
         
         //Dimension parentSize = this.getParent().getSize();
         //Dimension childSize = xtambah_pemesanan_detail.getSize();

         //xtambah_pemesanan_detail.setLocation((parentSize.width - childSize.width)/2, (parentSize.height-childSize.height)/2);
         //xtambah_pemesanan_detail.setVisible(true);  
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed
    
    private void clearText(){
        tId.setText("");
        tKode.setText("");
        cNamaSales.setSelectedIndex(0);
        cNamaKaryawan.setSelectedIndex(0);
       // tNamaSales.setText("");
        //tHpSales.setText("");
        tId.setEditable(false);
        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cNamaKaryawan;
    private javax.swing.JComboBox<String> cNamaSales;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField tId;
    private javax.swing.JTextField tKode;
    private com.toedter.calendar.JDateChooser tTgl;
    // End of variables declaration//GEN-END:variables
}
